config/routes.rb
Rails.application.routes.draw do
  resources :bus_schedules
  resources :list_bus_schedules
  resources :bus_lines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bus_line.rb
class BusLine < ApplicationRecord
  has_many :bus_schedules
  after_create_commit -> { broadcast_append_to 'bus_lines', partial: 'bus_lines/list_item' }
  after_update_commit -> { broadcast_update_to 'bus_lines', partial: 'bus_lines/list_item' }
  after_destroy_commit -> { broadcast_remove_to 'bus_lines' }
end

app/models/bus_schedule.rb
class BusSchedule < ApplicationRecord
  belongs_to :bus_line
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bus_lines_controller.rb
class BusLinesController < ApplicationController
  before_action :set_bus_line, only: %i[ show edit update destroy ]

  # GET /bus_lines
  def index
    @bus_lines = BusLine.all
  end

  # GET /bus_lines/1
  def show
  end

  # GET /bus_lines/new
  def new
    @bus_line = BusLine.new
  end

  # GET /bus_lines/1/edit
  def edit
  end

  # POST /bus_lines
  def create
    @bus_line = BusLine.new(bus_line_params)

    if @bus_line.save
      redirect_to @bus_line, notice: "Bus line was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bus_lines/1
  def update
    if @bus_line.update(bus_line_params)
      redirect_to @bus_line, notice: "Bus line was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /bus_lines/1
  def destroy
    @bus_line.destroy
    redirect_to bus_lines_url, notice: "Bus line was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_line
      @bus_line = BusLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bus_line_params
      params.require(:bus_line).permit(:name)
    end
end

app/controllers/bus_schedules_controller.rb
class BusSchedulesController < ApplicationController
  before_action :set_bus_schedule, only: %i[ show edit update destroy ]

  # GET /bus_schedules
  def index
    @bus_schedules = BusSchedule.all
  end

  # GET /bus_schedules/1
  def show
  end

  # GET /bus_schedules/new
  def new
    @bus_schedule = BusSchedule.new
  end

  # GET /bus_schedules/1/edit
  def edit
  end

  # POST /bus_schedules
  def create
    @bus_schedule = BusSchedule.new(bus_schedule_params)

    if @bus_schedule.save
      redirect_to @bus_schedule, notice: "Bus schedule was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bus_schedules/1
  def update
    if @bus_schedule.update(bus_schedule_params)
      redirect_to @bus_schedule, notice: "Bus schedule was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /bus_schedules/1
  def destroy
    @bus_schedule.destroy
    redirect_to bus_schedules_url, notice: "Bus schedule was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_schedule
      @bus_schedule = BusSchedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bus_schedule_params
      params.require(:bus_schedule).permit(:departure_hour, :departure_minute, :bus_line_id)
    end
end

app/controllers/list_bus_schedules_controller.rb
class ListBusSchedulesController < ApplicationController
  def index
    sleep 1
    @bus_schedules = BusSchedule.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_lines_helper.rb
module BusLinesHelper
end

app/helpers/bus_schedules_helper.rb
module BusSchedulesHelper
end

app/views/bus_lines/_bus_line.html.erb
<div id="<%= dom_id bus_line %>">
  <p>
    <strong>Name:</strong>
    <%= bus_line.name %>
  </p>

</div>

app/views/bus_lines/_form.html.erb
<%= form_with(model: bus_line) do |form| %>
  <% if bus_line.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bus_line.errors.count, "error") %> prohibited this bus_line from being saved:</h2>

      <ul>
        <% bus_line.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bus_lines/_list_item.html.erb
<tr id="<%= dom_id bus_line %>">
  <td class="name"><%= bus_line.name %></td>
  <td class="operation"><%= link_to "Show this bus line", bus_line, data: { turbo_frame: '_top' } %></td>
</tr>

app/views/bus_lines/edit.html.erb
<h1>Editing bus line</h1>

<%= render "form", bus_line: @bus_line %>

<br>

<div>
  <%= link_to "Show this bus line", @bus_line %> |
  <%= link_to "Back to bus lines", bus_lines_path %>
</div>

app/views/bus_lines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bus lines</h1>

<table class="bus-line-table">
  <thead>
    <tr>
      <th class="name">Name</th>
      <th class="operation">操作</th>
    </tr>
  </thead>
  <tbody id="bus_lines">
  </tbody>
</table>

<%= link_to "New bus line", new_bus_line_path %>

<%= turbo_stream_from 'bus_lines' %>

<% @bus_lines.each do |bus_line| %>
  <%= turbo_stream.append(:bus_lines, partial: "list_item", locals: { bus_line: bus_line }) %>
<% end %>

app/views/bus_lines/new.html.erb
<h1>New bus line</h1>

<%= render "form", bus_line: @bus_line %>

<br>

<div>
  <%= link_to "Back to bus lines", bus_lines_path %>
</div>

app/views/bus_lines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bus_line %>

<div>
  <%= link_to "Edit this bus line", edit_bus_line_path(@bus_line) %> |
  <%= link_to "Back to bus lines", bus_lines_path %>

  <%= button_to "Destroy this bus line", @bus_line, method: :delete %>
</div>

app/views/bus_schedules/_bus_schedule.html.erb
<div id="<%= dom_id bus_schedule %>">
  <p>
    <strong>Departure hour:</strong>
    <%= bus_schedule.departure_hour %>
  </p>

  <p>
    <strong>Departure minute:</strong>
    <%= bus_schedule.departure_minute %>
  </p>

  <p>
    <strong>Bus line:</strong>
    <%= bus_schedule.bus_line_id %>
  </p>

</div>

app/views/bus_schedules/_form.html.erb
<%= form_with(model: bus_schedule) do |form| %>
  <% if bus_schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bus_schedule.errors.count, "error") %> prohibited this bus_schedule from being saved:</h2>

      <ul>
        <% bus_schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :departure_hour, style: "display: block" %>
    <%= form.number_field :departure_hour %>
  </div>

  <div>
    <%= form.label :departure_minute, style: "display: block" %>
    <%= form.number_field :departure_minute %>
  </div>

  <div>
    <%= form.label :bus_line_id, style: "display: block" %>
    <%= form.number_field :bus_line_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bus_schedules/_schedule_table.html.erb
<%= turbo_frame_tag 'bus_schedules', src: bus_schedules.nil? ? list_bus_schedules_path : nil do %>
  <table class="bus-schedule-table" data-controller="schedule" data-schedule-selected-class="selected">
    <thead>
      <tr>
        <th class="departure-hour">時</td>
        <th class="departure-minute">分</td>
        <th class="line">路線</td>
        <th class="operation">操作</td>
      </tr>
    </thead>
    <tbody>
      <% if bus_schedules.nil? %>
      <tr>
        <td colspan="4" class="loading"><%= image_tag 'loading.gif' %></td>
      </tr>
      <% else %>
        <% bus_schedules.each do |bus_schedule| %>
        <tr data-schedule-target="row" data-action="click->schedule#selectRow">
          <td class="departure-hour"><%= bus_schedule.departure_hour %></td>
          <td class="departure-minute"><%= bus_schedule.departure_minute %></td>
          <td class="line"><%= bus_schedule.bus_line.name %></td>
          <td class="operation"><%= link_to "Show this bus schedule", bus_schedule, data: { turbo_frame: '_top' } %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/bus_schedules/edit.html.erb
<h1>Editing bus schedule</h1>

<%= render "form", bus_schedule: @bus_schedule %>

<br>

<div>
  <%= link_to "Show this bus schedule", @bus_schedule %> |
  <%= link_to "Back to bus schedules", bus_schedules_path %>
</div>

app/views/bus_schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bus schedules</h1>

<%= render partial: 'schedule_table', locals: { bus_schedules: nil } %>

<%= link_to "New bus schedule", new_bus_schedule_path %>

app/views/bus_schedules/new.html.erb
<h1>New bus schedule</h1>

<%= render "form", bus_schedule: @bus_schedule %>

<br>

<div>
  <%= link_to "Back to bus schedules", bus_schedules_path %>
</div>

app/views/bus_schedules/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bus_schedule %>

<div>
  <%= link_to "Edit this bus schedule", edit_bus_schedule_path(@bus_schedule) %> |
  <%= link_to "Back to bus schedules", bus_schedules_path %>

  <%= button_to "Destroy this bus schedule", @bus_schedule, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_bus_schedules/index.html.erb
<%= render partial: 'bus_schedules/schedule_table', locals: { bus_schedules: @bus_schedules } %>